# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a578ee885c2feb53b950d49e1bb181735376eaec7a90f8beff287fe309f6dda3e9bd790b7c269e5bbd1222c54fc1d9dcd9bfc70b799acc1c7250d8e4d6e1f6c0

test:
  secret_key_base: f06860c592f2a3f50402d4d84b51f33e983a60b0f9048a65e01fa5a31314f3cef31b18fe6ee3bb61358b88884e01c6f15205623a481fdaa33c44786b8ccf7667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
